apiVersion: v1
kind: Template
metadata:
  name: runtimes-inventory
objects:
  apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: runtimes-inventory
  spec:
    cyndi: {}
    database:
      name: runtimes
      version: 13
    deployments:
      - metadata: {}
        minReplicas: 1
        name: service
        podSpec:
          image: quay.io/cloudservices/insights-rbi-events:${IMAGE_TAG}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/live
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 35
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 120
          metadata: {}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/ready
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 35
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 120
          resources: {}
          volumeMounts:
            - mountPath: /tmp
              name: tmpdir
          volumes:
            - emptyDir: {}
              name: tmpdir
        webServices:
          metrics: {}
          private: {}
          public:
            # This can override the service name
            apiPath: insights-rbi-events
            enabled: true
    kafkaTopics:
      - partitions: 3
        replicas: 3
        topicName: platform.upload.runtimes-java-general
    dependencies:
      - ingress
      - host-inventory
    testing:
      iqePlugin: ''
